language: node_js

node_js:
  - stable
  - '6'
  - '8'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- version 0.23.2
  - export PATH="$HOME/.yarn/bin:$PATH"
install: yarn install
script: yarn workspace @magicspace/tslint-rules test
